/*
 * Generated by JasperReports - 12/12/11 10:34 �
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class attendanceStudentsReport extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_commitDate = null;
    private JRFillParameter parameter_termName = null;
    private JRFillParameter parameter_repDate = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_imagePath = null;
    private JRFillParameter parameter_centerName = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_tutorName = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_classNo = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_commitDateLabel = null;
    private JRFillParameter parameter_isCommit = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_courseName = null;
    private JRFillField field_studName = null;
    private JRFillField field_finalTheoritical = null;
    private JRFillField field_assign2 = null;
    private JRFillField field_assign1 = null;
    private JRFillField field_status = null;
    private JRFillField field_mid1 = null;
    private JRFillField field_studId = null;
    private JRFillField field_mark = null;
    private JRFillField field_serial = null;
    private JRFillField field_finalPractical = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_commitDate = (JRFillParameter)pm.get("commitDate");
        parameter_termName = (JRFillParameter)pm.get("termName");
        parameter_repDate = (JRFillParameter)pm.get("repDate");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_imagePath = (JRFillParameter)pm.get("imagePath");
        parameter_centerName = (JRFillParameter)pm.get("centerName");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_tutorName = (JRFillParameter)pm.get("tutorName");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_classNo = (JRFillParameter)pm.get("classNo");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_commitDateLabel = (JRFillParameter)pm.get("commitDateLabel");
        parameter_isCommit = (JRFillParameter)pm.get("isCommit");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_courseName = (JRFillParameter)pm.get("courseName");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_studName = (JRFillField)fm.get("studName");
        field_finalTheoritical = (JRFillField)fm.get("finalTheoritical");
        field_assign2 = (JRFillField)fm.get("assign2");
        field_assign1 = (JRFillField)fm.get("assign1");
        field_status = (JRFillField)fm.get("status");
        field_mid1 = (JRFillField)fm.get("mid1");
        field_studId = (JRFillField)fm.get("studId");
        field_mark = (JRFillField)fm.get("mark");
        field_serial = (JRFillField)fm.get("serial");
        field_finalPractical = (JRFillField)fm.get("finalPractical");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (Integer)(new Integer(1));
                break;
            }
            case 1 : 
            {
                value = (Integer)(new Integer(1));
                break;
            }
            case 2 : 
            {
                value = (Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (Integer)(new Integer(0));
                break;
            }
            case 4 : 
            {
                value = (Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (String)(((String)parameter_termName.getValue()));
                break;
            }
            case 9 : 
            {
                value = (String)(((String)parameter_classNo.getValue()));
                break;
            }
            case 10 : 
            {
                value = (String)(((String)parameter_tutorName.getValue()));
                break;
            }
            case 11 : 
            {
                value = (String)(((String)parameter_courseName.getValue()));
                break;
            }
            case 12 : 
            {
                value = (String)(((String)parameter_centerName.getValue()));
                break;
            }
            case 13 : 
            {
                value = (String)(((String)parameter_imagePath.getValue()));
                break;
            }
            case 14 : 
            {
                value = (String)(((String)parameter_commitDate.getValue()));
                break;
            }
            case 15 : 
            {
                value = (String)(((String)parameter_isCommit.getValue()));
                break;
            }
            case 16 : 
            {
                value = (String)(((String)parameter_commitDateLabel.getValue()));
                break;
            }
            case 17 : 
            {
                value = (String)(((String)field_serial.getValue()));
                break;
            }
            case 18 : 
            {
                value = (String)(((String)field_studId.getValue()));
                break;
            }
            case 19 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 20 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 21 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 22 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 23 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 24 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 25 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 26 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 27 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 28 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 29 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 30 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 31 : 
            {
                value = (String)(((String)field_studName.getValue()));
                break;
            }
            case 32 : 
            {
                value = (Integer)(((Integer)variable_PAGE_NUMBER.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (Integer)(new Integer(1));
                break;
            }
            case 1 : 
            {
                value = (Integer)(new Integer(1));
                break;
            }
            case 2 : 
            {
                value = (Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (Integer)(new Integer(0));
                break;
            }
            case 4 : 
            {
                value = (Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (String)(((String)parameter_termName.getValue()));
                break;
            }
            case 9 : 
            {
                value = (String)(((String)parameter_classNo.getValue()));
                break;
            }
            case 10 : 
            {
                value = (String)(((String)parameter_tutorName.getValue()));
                break;
            }
            case 11 : 
            {
                value = (String)(((String)parameter_courseName.getValue()));
                break;
            }
            case 12 : 
            {
                value = (String)(((String)parameter_centerName.getValue()));
                break;
            }
            case 13 : 
            {
                value = (String)(((String)parameter_imagePath.getValue()));
                break;
            }
            case 14 : 
            {
                value = (String)(((String)parameter_commitDate.getValue()));
                break;
            }
            case 15 : 
            {
                value = (String)(((String)parameter_isCommit.getValue()));
                break;
            }
            case 16 : 
            {
                value = (String)(((String)parameter_commitDateLabel.getValue()));
                break;
            }
            case 17 : 
            {
                value = (String)(((String)field_serial.getOldValue()));
                break;
            }
            case 18 : 
            {
                value = (String)(((String)field_studId.getOldValue()));
                break;
            }
            case 19 : 
            {
                value = (String)(((String)field_assign1.getOldValue()));
                break;
            }
            case 20 : 
            {
                value = (String)(((String)field_assign1.getOldValue()));
                break;
            }
            case 21 : 
            {
                value = (String)(((String)field_assign1.getOldValue()));
                break;
            }
            case 22 : 
            {
                value = (String)(((String)field_assign1.getOldValue()));
                break;
            }
            case 23 : 
            {
                value = (String)(((String)field_assign1.getOldValue()));
                break;
            }
            case 24 : 
            {
                value = (String)(((String)field_assign1.getOldValue()));
                break;
            }
            case 25 : 
            {
                value = (String)(((String)field_assign1.getOldValue()));
                break;
            }
            case 26 : 
            {
                value = (String)(((String)field_assign1.getOldValue()));
                break;
            }
            case 27 : 
            {
                value = (String)(((String)field_assign1.getOldValue()));
                break;
            }
            case 28 : 
            {
                value = (String)(((String)field_assign1.getOldValue()));
                break;
            }
            case 29 : 
            {
                value = (String)(((String)field_assign1.getOldValue()));
                break;
            }
            case 30 : 
            {
                value = (String)(((String)field_assign1.getOldValue()));
                break;
            }
            case 31 : 
            {
                value = (String)(((String)field_studName.getOldValue()));
                break;
            }
            case 32 : 
            {
                value = (Integer)(((Integer)variable_PAGE_NUMBER.getOldValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (Integer)(new Integer(1));
                break;
            }
            case 1 : 
            {
                value = (Integer)(new Integer(1));
                break;
            }
            case 2 : 
            {
                value = (Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (Integer)(new Integer(0));
                break;
            }
            case 4 : 
            {
                value = (Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (String)(((String)parameter_termName.getValue()));
                break;
            }
            case 9 : 
            {
                value = (String)(((String)parameter_classNo.getValue()));
                break;
            }
            case 10 : 
            {
                value = (String)(((String)parameter_tutorName.getValue()));
                break;
            }
            case 11 : 
            {
                value = (String)(((String)parameter_courseName.getValue()));
                break;
            }
            case 12 : 
            {
                value = (String)(((String)parameter_centerName.getValue()));
                break;
            }
            case 13 : 
            {
                value = (String)(((String)parameter_imagePath.getValue()));
                break;
            }
            case 14 : 
            {
                value = (String)(((String)parameter_commitDate.getValue()));
                break;
            }
            case 15 : 
            {
                value = (String)(((String)parameter_isCommit.getValue()));
                break;
            }
            case 16 : 
            {
                value = (String)(((String)parameter_commitDateLabel.getValue()));
                break;
            }
            case 17 : 
            {
                value = (String)(((String)field_serial.getValue()));
                break;
            }
            case 18 : 
            {
                value = (String)(((String)field_studId.getValue()));
                break;
            }
            case 19 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 20 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 21 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 22 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 23 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 24 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 25 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 26 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 27 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 28 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 29 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 30 : 
            {
                value = (String)(((String)field_assign1.getValue()));
                break;
            }
            case 31 : 
            {
                value = (String)(((String)field_studName.getValue()));
                break;
            }
            case 32 : 
            {
                value = (Integer)(((Integer)variable_PAGE_NUMBER.getEstimatedValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
