/*
 * Generated by JasperReports - 02/03/09 02:03 ã
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import java.util.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class Test1 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_reportDate = null;
    private JRFillParameter parameter_studTawjehiAvgLabel = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_centerName = null;
    private JRFillParameter parameter_studTawjehiAvg = null;
    private JRFillParameter parameter_total = null;
    private JRFillParameter parameter_studLevelLabel = null;
    private JRFillParameter parameter_studCumAvg = null;
    private JRFillParameter parameter_studLoanProgramPath = null;
    private JRFillParameter parameter_conn2 = null;
    private JRFillParameter parameter_scholarship = null;
    private JRFillParameter parameter_termId = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_finantialReportPath = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_studCumAvgLabel = null;
    private JRFillParameter parameter_studSpec = null;
    private JRFillParameter parameter_pageNumber = null;
    private JRFillParameter parameter_bankReportPath = null;
    private JRFillParameter parameter_oldBalance = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_studName = null;
    private JRFillParameter parameter_reportType = null;
    private JRFillParameter parameter_conn1 = null;
    private JRFillParameter parameter_imagePath = null;
    private JRFillParameter parameter_reportTitle = null;
    private JRFillParameter parameter_reportSerial = null;
    private JRFillParameter parameter_payLastDate = null;
    private JRFillParameter parameter_totalByWord = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_hoursSum = null;
    private JRFillParameter parameter_centerNo = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_studId = null;
    private JRFillParameter parameter_regApprovedDate = null;
    private JRFillParameter parameter_studLevel = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillField field_to = null;
    private JRFillField field_day = null;
    private JRFillField field_tutorName = null;
    private JRFillField field_crsId = null;
    private JRFillField field_classNo = null;
    private JRFillField field_buildingNo = null;
    private JRFillField field_courseActionType = null;
    private JRFillField field_crsName = null;
    private JRFillField field_from = null;
    private JRFillField field_hours = null;
    private JRFillField field_serial = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_financialGroup_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_reportDate = (JRFillParameter)pm.get("reportDate");
        parameter_studTawjehiAvgLabel = (JRFillParameter)pm.get("studTawjehiAvgLabel");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_centerName = (JRFillParameter)pm.get("centerName");
        parameter_studTawjehiAvg = (JRFillParameter)pm.get("studTawjehiAvg");
        parameter_total = (JRFillParameter)pm.get("total");
        parameter_studLevelLabel = (JRFillParameter)pm.get("studLevelLabel");
        parameter_studCumAvg = (JRFillParameter)pm.get("studCumAvg");
        parameter_studLoanProgramPath = (JRFillParameter)pm.get("studLoanProgramPath");
        parameter_conn2 = (JRFillParameter)pm.get("conn2");
        parameter_scholarship = (JRFillParameter)pm.get("scholarship");
        parameter_termId = (JRFillParameter)pm.get("termId");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_finantialReportPath = (JRFillParameter)pm.get("finantialReportPath");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_studCumAvgLabel = (JRFillParameter)pm.get("studCumAvgLabel");
        parameter_studSpec = (JRFillParameter)pm.get("studSpec");
        parameter_pageNumber = (JRFillParameter)pm.get("pageNumber");
        parameter_bankReportPath = (JRFillParameter)pm.get("bankReportPath");
        parameter_oldBalance = (JRFillParameter)pm.get("oldBalance");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_studName = (JRFillParameter)pm.get("studName");
        parameter_reportType = (JRFillParameter)pm.get("reportType");
        parameter_conn1 = (JRFillParameter)pm.get("conn1");
        parameter_imagePath = (JRFillParameter)pm.get("imagePath");
        parameter_reportTitle = (JRFillParameter)pm.get("reportTitle");
        parameter_reportSerial = (JRFillParameter)pm.get("reportSerial");
        parameter_payLastDate = (JRFillParameter)pm.get("payLastDate");
        parameter_totalByWord = (JRFillParameter)pm.get("totalByWord");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_hoursSum = (JRFillParameter)pm.get("hoursSum");
        parameter_centerNo = (JRFillParameter)pm.get("centerNo");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_studId = (JRFillParameter)pm.get("studId");
        parameter_regApprovedDate = (JRFillParameter)pm.get("regApprovedDate");
        parameter_studLevel = (JRFillParameter)pm.get("studLevel");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_to = (JRFillField)fm.get("to");
        field_day = (JRFillField)fm.get("day");
        field_tutorName = (JRFillField)fm.get("tutorName");
        field_crsId = (JRFillField)fm.get("crsId");
        field_classNo = (JRFillField)fm.get("classNo");
        field_buildingNo = (JRFillField)fm.get("buildingNo");
        field_courseActionType = (JRFillField)fm.get("courseActionType");
        field_crsName = (JRFillField)fm.get("crsName");
        field_from = (JRFillField)fm.get("from");
        field_hours = (JRFillField)fm.get("hours");
        field_serial = (JRFillField)fm.get("serial");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_financialGroup_COUNT = (JRFillVariable)vm.get("financialGroup_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 10 : 
            {
                value = (java.lang.Object)(null);
                break;
            }
            case 11 : 
            {
                value = (java.lang.Object)(((java.lang.Object)parameter_conn1.getValue()));
                break;
            }
            case 12 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(((java.lang.Object)parameter_conn1.getValue()));
                break;
            }
            case 13 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_finantialReportPath.getValue()));
                break;
            }
            case 14 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_hoursSum.getValue()));
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_total.getValue()));
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_scholarship.getValue()));
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_oldBalance.getValue()));
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_payLastDate.getValue()));
                break;
            }
            case 19 : 
            {
                value = (java.lang.Object)(((java.lang.Object)parameter_conn2.getValue()));
                break;
            }
            case 20 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(((java.lang.Object)parameter_conn2.getValue()));
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_bankReportPath.getValue()));
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_totalByWord.getValue()));
                break;
            }
            case 23 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_studTawjehiAvg.getValue()));
                break;
            }
            case 24 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_studLevelLabel.getValue()));
                break;
            }
            case 25 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_studCumAvg.getValue()));
                break;
            }
            case 26 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_studCumAvgLabel.getValue()));
                break;
            }
            case 27 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_studTawjehiAvgLabel.getValue()));
                break;
            }
            case 28 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_studLevel.getValue()));
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_studLoanProgramPath.getValue()));
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_imagePath.getValue()));
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_studName.getValue()));
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_studId.getValue()));
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_studSpec.getValue()));
                break;
            }
            case 34 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_regApprovedDate.getValue()));
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_reportSerial.getValue()));
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_reportType.getValue()));
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_centerName.getValue()));
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_termId.getValue()));
                break;
            }
            case 39 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_centerNo.getValue()));
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_reportDate.getValue()));
                break;
            }
            case 41 : 
            {
                value = (java.lang.String)(((java.lang.String)field_crsName.getValue()));
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)(((java.lang.String)field_serial.getValue()));
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)(((java.lang.String)field_crsId.getValue()));
                break;
            }
            case 44 : 
            {
                value = (java.lang.String)(((java.lang.String)field_hours.getValue()));
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)(((java.lang.String)field_classNo.getValue()));
                break;
            }
            case 46 : 
            {
                value = (java.lang.String)(((java.lang.String)field_tutorName.getValue()));
                break;
            }
            case 47 : 
            {
                value = (java.lang.String)(((java.lang.String)field_day.getValue()));
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(((java.lang.String)field_from.getValue()));
                break;
            }
            case 49 : 
            {
                value = (java.lang.String)(((java.lang.String)field_to.getValue()));
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(((java.lang.String)field_buildingNo.getValue()));
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_pageNumber.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 10 : 
            {
                value = (java.lang.Object)(null);
                break;
            }
            case 11 : 
            {
                value = (java.lang.Object)(((java.lang.Object)parameter_conn1.getValue()));
                break;
            }
            case 12 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(((java.lang.Object)parameter_conn1.getValue()));
                break;
            }
            case 13 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_finantialReportPath.getValue()));
                break;
            }
            case 14 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_hoursSum.getValue()));
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_total.getValue()));
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_scholarship.getValue()));
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_oldBalance.getValue()));
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_payLastDate.getValue()));
                break;
            }
            case 19 : 
            {
                value = (java.lang.Object)(((java.lang.Object)parameter_conn2.getValue()));
                break;
            }
            case 20 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(((java.lang.Object)parameter_conn2.getValue()));
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_bankReportPath.getValue()));
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_totalByWord.getValue()));
                break;
            }
            case 23 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_studTawjehiAvg.getValue()));
                break;
            }
            case 24 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_studLevelLabel.getValue()));
                break;
            }
            case 25 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_studCumAvg.getValue()));
                break;
            }
            case 26 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_studCumAvgLabel.getValue()));
                break;
            }
            case 27 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_studTawjehiAvgLabel.getValue()));
                break;
            }
            case 28 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_studLevel.getValue()));
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_studLoanProgramPath.getValue()));
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_imagePath.getValue()));
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_studName.getValue()));
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_studId.getValue()));
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_studSpec.getValue()));
                break;
            }
            case 34 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_regApprovedDate.getValue()));
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_reportSerial.getValue()));
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_reportType.getValue()));
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_centerName.getValue()));
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_termId.getValue()));
                break;
            }
            case 39 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_centerNo.getValue()));
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_reportDate.getValue()));
                break;
            }
            case 41 : 
            {
                value = (java.lang.String)(((java.lang.String)field_crsName.getOldValue()));
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)(((java.lang.String)field_serial.getOldValue()));
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)(((java.lang.String)field_crsId.getOldValue()));
                break;
            }
            case 44 : 
            {
                value = (java.lang.String)(((java.lang.String)field_hours.getOldValue()));
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)(((java.lang.String)field_classNo.getOldValue()));
                break;
            }
            case 46 : 
            {
                value = (java.lang.String)(((java.lang.String)field_tutorName.getOldValue()));
                break;
            }
            case 47 : 
            {
                value = (java.lang.String)(((java.lang.String)field_day.getOldValue()));
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(((java.lang.String)field_from.getOldValue()));
                break;
            }
            case 49 : 
            {
                value = (java.lang.String)(((java.lang.String)field_to.getOldValue()));
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(((java.lang.String)field_buildingNo.getOldValue()));
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_pageNumber.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 10 : 
            {
                value = (java.lang.Object)(null);
                break;
            }
            case 11 : 
            {
                value = (java.lang.Object)(((java.lang.Object)parameter_conn1.getValue()));
                break;
            }
            case 12 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(((java.lang.Object)parameter_conn1.getValue()));
                break;
            }
            case 13 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_finantialReportPath.getValue()));
                break;
            }
            case 14 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_hoursSum.getValue()));
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_total.getValue()));
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_scholarship.getValue()));
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_oldBalance.getValue()));
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_payLastDate.getValue()));
                break;
            }
            case 19 : 
            {
                value = (java.lang.Object)(((java.lang.Object)parameter_conn2.getValue()));
                break;
            }
            case 20 : 
            {
                value = (net.sf.jasperreports.engine.JRDataSource)(((java.lang.Object)parameter_conn2.getValue()));
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_bankReportPath.getValue()));
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_totalByWord.getValue()));
                break;
            }
            case 23 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_studTawjehiAvg.getValue()));
                break;
            }
            case 24 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_studLevelLabel.getValue()));
                break;
            }
            case 25 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_studCumAvg.getValue()));
                break;
            }
            case 26 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_studCumAvgLabel.getValue()));
                break;
            }
            case 27 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_studTawjehiAvgLabel.getValue()));
                break;
            }
            case 28 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_studLevel.getValue()));
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_studLoanProgramPath.getValue()));
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_imagePath.getValue()));
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_studName.getValue()));
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_studId.getValue()));
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_studSpec.getValue()));
                break;
            }
            case 34 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_regApprovedDate.getValue()));
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_reportSerial.getValue()));
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_reportType.getValue()));
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_centerName.getValue()));
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_termId.getValue()));
                break;
            }
            case 39 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_centerNo.getValue()));
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_reportDate.getValue()));
                break;
            }
            case 41 : 
            {
                value = (java.lang.String)(((java.lang.String)field_crsName.getValue()));
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)(((java.lang.String)field_serial.getValue()));
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)(((java.lang.String)field_crsId.getValue()));
                break;
            }
            case 44 : 
            {
                value = (java.lang.String)(((java.lang.String)field_hours.getValue()));
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)(((java.lang.String)field_classNo.getValue()));
                break;
            }
            case 46 : 
            {
                value = (java.lang.String)(((java.lang.String)field_tutorName.getValue()));
                break;
            }
            case 47 : 
            {
                value = (java.lang.String)(((java.lang.String)field_day.getValue()));
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(((java.lang.String)field_from.getValue()));
                break;
            }
            case 49 : 
            {
                value = (java.lang.String)(((java.lang.String)field_to.getValue()));
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(((java.lang.String)field_buildingNo.getValue()));
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_pageNumber.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
